import { test } from 'node:test';
import assert from 'node:assert/strict';
import Matter from 'matter-js';
import { Game } from '../src/game.js';
import { CONFIG as C, STAGES } from '../src/config.js';
const steps=(g,n)=>{for(let i=0;i<n;i++)g.step();};
const mergeNow=(g,level)=>{const a=g.add(level,120,420),b=g.add(level,300,420);g.queuePairs([{bodyA:a,bodyB:b}]);g.mergePending();};

for(let level=1;level<7;level++)test(`第一关 ${level}+${level} 升级且只计分一次`,()=>{
  const g=new Game();mergeNow(g,level);assert.equal(g.bodies.size,1);assert.equal([...g.bodies.values()][0].plugin.level,level+1);assert.equal(g.score,STAGES[0].points[level]);
});
test('第一关 7+7 消失、加 128 分并只增加一次进度',()=>{let progress=[];const g=new Game({onProgress:(n,t)=>progress.push([n,t])});mergeNow(g,7);assert.equal(g.bodies.size,0);assert.equal(g.engine.world.bodies.length,3);assert.equal(g.score,128);assert.equal(g.highestLevelClearCount,1);assert.deepEqual(progress.at(-1),[1,5]);});
test('第一关四次最高级消除不完成，第五次只触发一次完成并暂停',()=>{let completed=0;const g=new Game({onStageComplete:()=>completed++});for(let i=0;i<4;i++)mergeNow(g,7);assert.equal(g.paused,false);mergeNow(g,7);assert.equal(g.paused,true);assert.equal(completed,1);assert.equal(g.score,640);assert.equal(g.drop(),false);g.mergePending();assert.equal(completed,1);});
test('点击进入第二关会清场、保留总分并隐藏关卡进度语义',()=>{const changes=[];const g=new Game({onStageChange:s=>changes.push(s.id)});for(let i=0;i<5;i++)mergeNow(g,7);assert.equal(g.continueToNextStage(),true);assert.equal(g.stageIndex,1);assert.equal(g.stage.title,'合成大嫂子');assert.equal(g.score,640);assert.equal(g.highestLevelClearCount,0);assert.equal(g.bodies.size,0);assert.equal(g.engine.world.bodies.length,3);assert.equal(g.paused,false);assert.deepEqual(changes,[1,2]);});
test('第二关 1 至 5 级合并，6+6 消除加 64 分且不通关',()=>{const g=new Game();for(let i=0;i<5;i++)mergeNow(g,7);g.continueToNextStage();const carried=g.score;for(let level=1;level<6;level++){const before=g.score;mergeNow(g,level);assert.equal(g.score-before,STAGES[1].points[level]);g.bodies.clear();Matter.Composite.clear(g.engine.world,false);Matter.Composite.add(g.engine.world,[Matter.Bodies.rectangle(-25,C.height/2,50,C.height*4,{isStatic:true}),Matter.Bodies.rectangle(C.width+25,C.height/2,50,C.height*4,{isStatic:true}),Matter.Bodies.rectangle(C.width/2,C.height+25,C.width+100,50,{isStatic:true})]);}mergeNow(g,6);assert.equal(g.score,carried+2+4+8+16+32+64);assert.equal(g.paused,false);assert.equal(g.stageIndex,1);});
test('第二关重新开始回到第一关、总分与进度归零',()=>{const g=new Game();for(let i=0;i<5;i++)mergeNow(g,7);g.continueToNextStage();mergeNow(g,1);g.reset();assert.equal(g.stageIndex,0);assert.equal(g.score,0);assert.equal(g.highestLevelClearCount,0);assert.equal(g.bodies.size,0);assert.equal(g.engine.world.bodies.length,3);});
test('第一关与第二关都沿用危险线失败，第二关失败后重开回第一关',()=>{const g=new Game();let b=g.add(1,100,100,0);Matter.Body.setStatic(b,true);steps(g,115);assert.equal(g.over,true);g.reset();for(let i=0;i<5;i++)mergeNow(g,7);g.continueToNextStage();b=g.add(1,100,100,0);Matter.Body.setStatic(b,true);steps(g,115);assert.equal(g.over,true);g.reset();assert.equal(g.stageIndex,0);assert.equal(g.score,0);assert.equal(g.highestLevelClearCount,0);});
test('两关碰撞半径分别严格使用基础尺寸的 1.05 与 1.10 倍',()=>{const base=[.085,.125,.175,.24,.32,.42];const g=new Game();for(let level=1;level<=7;level++)assert.equal(g.radius(level),C.width*STAGES[0].diameterRatios[level-1]/2);assert.deepEqual(STAGES[0].diameterRatios.slice(0,6),base.map(v=>Number((v*1.05).toFixed(4))));for(let i=0;i<5;i++)mergeNow(g,7);g.continueToNextStage();assert.deepEqual(STAGES[1].diameterRatios,base.map(v=>Number((v*1.10).toFixed(4))));for(let level=1;level<=6;level++){const b=g.add(level,210,300);assert.equal(b.circleRadius,g.radius(level));}});
test('共享物体、重复碰撞和已删除引用不能重复合并',()=>{const g=new Game();const a=g.add(1,100,400),b=g.add(1,140,400),c=g.add(1,180,400),pairs=[{bodyA:a,bodyB:b},{bodyA:b,bodyB:c},{bodyA:a,bodyB:b}];g.queuePairs(pairs);g.queuePairs(pairs);g.mergePending();g.queuePairs(pairs);g.mergePending();assert.equal(g.score,2);assert.equal(g.bodies.size,2);});
test('合并产生新碰撞并继续连锁',()=>{const g=new Game();const a=g.add(1,180,450),b=g.add(1,220,450);g.add(2,200,405);g.queuePairs([{bodyA:a,bodyB:b}]);g.mergePending();steps(g,120);assert.equal(g.bodies.size,1);assert.equal([...g.bodies.values()][0].plugin.level,3);assert.equal(g.score,6);});
test('连续投放有冷却且随机仅含低等级',()=>{const g=new Game();for(let i=0;i<1000;i++)assert.ok([1,2,3].includes(g.choose()));assert.ok(g.drop());for(let i=0;i<20;i++)assert.equal(g.drop(),false);steps(g,30);assert.ok(g.drop());});
test('危险线延迟、结束冻结与重置不重复绑定事件',()=>{let ended=0;const g=new Game({onEnd:()=>ended++});const b=g.add(1,100,100,0);Matter.Body.setStatic(b,true);steps(g,60);assert.equal(g.over,false);steps(g,55);assert.equal(g.over,true);assert.equal(ended,1);const t=g.time;steps(g,20);assert.equal(g.time,t);g.reset();g.reset();assert.equal(g.engine.events.collisionStart.length,1);assert.equal(g.engine.events.collisionActive.length,1);});
test('短暂越线恢复不失败，投放宽限期仍生效',()=>{const g=new Game();const b=g.add(1,100,100,0);Matter.Body.setStatic(b,true);steps(g,70);Matter.Body.setPosition(b,{x:100,y:300});steps(g,80);assert.equal(g.over,false);assert.equal(b.plugin.dangerSince,null);const fresh=g.add(1,150,100);Matter.Body.setStatic(fresh,true);steps(g,60);assert.equal(g.over,false);});
test('边界限制与 Canvas 白圆半径和物理半径一致',()=>{const g=new Game();g.move(-100);assert.ok(g.x>=g.radius(g.current));g.drop();for(const b of g.bodies.values())assert.equal(b.circleRadius,g.radius(b.plugin.level));g.move(1000);assert.ok(g.x<=C.width-g.radius(g.current));});
test('关卡素材配置分别包含 01–07 和原 1–6',()=>{assert.equal(STAGES[0].assets.length,7);assert.equal(STAGES[1].assets.length,6);STAGES[0].assets.forEach((src,i)=>assert.match(src,new RegExp(`0${i+1}\\.png$`)));STAGES[1].assets.forEach((src,i)=>assert.match(src,new RegExp(`/${i+1}\\.png$`)));});
